
spring:
  datasource:
    hikari:
      schema: "master"
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    password: "root"
    username: "root"
    url: "jdbc:postgresql://localhost:5432/test_db?currentSchema=master"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 1000
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    liquibase-schema: master

#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true